### ISSUE TITLE
Elemental imbuements not working.

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#749]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Imbue weapon with ice imbuement.
2. Equip weapon.
3. Try "exori" spell. 

### Expected behaviour

The creature should take ice dmg if not immune. 
### Actual behaviour

No ice damage is present.

**Comment by malucooo** [comment]
make a video plz...

**Comment by H0ltman** [comment]
Recommend a software for that task? I'm sure I can find something. 

I assure you this is not working correctly. A quick look at the code should illustrate that beyond doubt. 

I'll add video when I can.

**Comment by Nicholasz23** [comment]
https://streamable.com/1y6h5

**Comment by H0ltman** [comment]
Thanks Nicholasz.

**Comment by malucooo** [comment]
fixed in last commit! thank you for report!!!

**Comment by H0ltman** [comment]
Not fixed. 

No elemental damage on any weapon I tested. It still doesn't work.

**Comment by malucooo** [comment]
Update ur datapack

**Comment by H0ltman** [comment]
`
	<event class="Player" method="onCombatSpell" enabled="1" />`

missed that, thank you Malucooo.
